//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.06.06 at 12:17:03 BST 
//


package edu.sdsc.matrix.srb.parser;


/**
 * Java content class for OpResult complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="OpResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="returnValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addlComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="prepareTicketResult" type="{http://www.teragrid.org/schemas/datagrid}PrepareTicketResult"/>
 *           &lt;element name="downloadDataSetResult" type="{http://www.teragrid.org/schemas/datagrid}DownloadDataSetResult"/>
 *           &lt;element name="listResult" type="{http://www.teragrid.org/schemas/datagrid}ListResult"/>
 *           &lt;element name="seekNReadResult" type="{http://www.teragrid.org/schemas/datagrid}SeekNReadResult"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface OpResult {


    edu.sdsc.matrix.srb.parser.SeekNReadResult getSeekNReadResult();

    void setSeekNReadResult(edu.sdsc.matrix.srb.parser.SeekNReadResult value);

    edu.sdsc.matrix.srb.parser.ListResult getListResult();

    void setListResult(edu.sdsc.matrix.srb.parser.ListResult value);

    edu.sdsc.matrix.srb.parser.PrepareTicketResult getPrepareTicketResult();

    void setPrepareTicketResult(edu.sdsc.matrix.srb.parser.PrepareTicketResult value);

    java.lang.String getAddlComments();

    void setAddlComments(java.lang.String value);

    java.lang.String getDescription();

    void setDescription(java.lang.String value);

    edu.sdsc.matrix.srb.parser.DownloadDataSetResult getDownloadDataSetResult();

    void setDownloadDataSetResult(edu.sdsc.matrix.srb.parser.DownloadDataSetResult value);

    int getReturnValue();

    void setReturnValue(int value);

}
