#!/bin/sh
# chkconfig: 12345 98 01
# description: Startup script for Storage Resource Broker (SRB)


id srb > /dev/null 2>&1
if [ $? = 1 ]
then
echo "no srb user..."
exit 1
fi

# Source the library functions
. /etc/rc.d/init.d/functions

# lets see how we were called
case "$1" in
  start) 
	echo "Starting SRB: "
        su -c '~/bin/runsrb ~/bin' srb
#        su -c '~/bin/srbd' srb
  ;;
  stop)
	echo "Stopping SRB: "
        su -c '~/bin/killsrb now' srb
#        su -c '~/bin/srbd stop' srb
  ;;
  restart)
	echo "Restarting SRB"
	$0 stop
	$0 start
	echo "done."
  ;;
  status)
        list=`ls ~srb/bin/srbMaster*`
        for file in $list
        do
          status $file
        done
  ;;
  *)
	echo "Usage: srb {start|stop|restart|status}"
	exit 1
esac
