.\" For ascii version, process this file with
.\" groff -man -Tascii Shelp.1
.\"
.TH Shelp 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Shelp \- Displays a list of all available SRB S-commands
.SH SYNOPSIS
.B Shelp
.SH DESCRIPTION
.B "Shelp "
Displays a list of all available SRB S-commands, as well as a short
description of what it's for.
.PP
.SH "OPTIONS"
none
.SH "SEE ALSO"
.BR Sinit (1),
.BR Senv (1),
.BR Sexit (1)


