#!/bin/csh
echo 'Usage Slstest <count> <srbObjName>'
set startt = `date`
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 &
repeat $1 /misc/srb/sekar/srb/SRB3_0_0rajafm/utilities/bin/Sls $2 
set endt = `date`
echo num of Sls = ` expr $1 \* 10`
echo start time = $startt
echo endin time = $endt
exit
