.\" For ascii version, process this file with
.\" groff -man -Tascii S.1
.\"
.TH SdelValue 1 "July 2004 " "Storage Resource Broker" "Admin SRB Commands"
.SH NAME
SdelValue \- Deletes a SRB entry.
.SH SYNOPSIS
.BR "SdelValue <" operationType >
.I DeleteValue
.SH DESCRIPTION
.B "SdelValue "
deletes a SRB entry.
.BR < operationType >
determines which type of entry is to be deleted.
.I DeleteValue
is the entry you wish to delete.
.PP
.SH "OPERATIONTYPES"
.TP 0.5i
.B "User "
Deletes a user.
.TP 0.5i
.B "PhyResource "
Deletes a physical resource.
.TP 0.5i
.B "Location "
Deletes a location.
.SH "SEE ALSO"
.BR Singestuser (1),
.BR SmodifyUser (1),
.BR SmodR (1),
.BR Sregisterlocation (1),
.BR Sregisterresource (1)
