.\" For ascii version, process this file with
.\" groff -man -Tascii Spasswd.1
.\"
.TH Spasswd 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Spasswd \- changes password of current user
.SH SYNOPSIS
.B Spasswd
.SH DESCRIPTION
.B "Spasswd"
changes the current user's password both in the
Meta Catalog as well as in the Client Authorization Environment
file. The Client Authorization Environment file is normally
located in  ~/.srb/.MdasAuth
.sp
The password change persists across sessions with SRB.
.sp
Users should have write permissions in the path where the Client
Authorization Environment file is located.
.sp
If the Sauth secure password storing system is being used, Spasswd
will update the Sauth file (.srbAuthFile) instead of the .MdasAuth 
file.
.PP
.SH "OPTIONS"
none
.SH "SEE ALSO"
.BR Sinit (1),
.BR Sauth (1)

