.\" For ascii version, process this file with
.\" groff -man -Tascii S.1
.\"
.TH Singestgroup 1 "April 2004 " "Storage Resource Broker" "Admin SRB Commands"
.SH NAME
Singestgroup \- adds a  group user  account to a SRB grid.
.SH SYNOPSIS
.B Singestgroup
.I NewGroupName NewGroupPassword NewGroupAddress NewGroupPhone NewGroupEmail 
.SH DESCRIPTION
.B "Singestgroup "
adds a group account to a SRB grid. Be careful to quote fields with spaces.
.PP
.SH "FIELDS"
.TP 0.5i
.B "NewGroupName "
the name for the group
.TP 0.5i
.B "NewGroupPassword "
the account password
.TP 0.5i
.B "NewGroupAddress "
the address of the group
.TP 0.5i
.B "NewGroupPhone "
the phone number of the group
.TP 0.5i
.B "NewGroupEmail "
the email of the group
.SH "SEE ALSO"
.BR SmodifyUser (1),
.BR Singestuser (1),
.BR SgetU (1),
.BR Stoken (1)
