.\" For ascii version, process this file with
.\" groff -man -Tascii S.1
.\"
.TH S 1 "Sept 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Spushmeta \- ingests metadata in bulk into a SRB.
.SH SYNOPSIS
.B Spushmeta
.BI "[-h] " inputMetadatFile "|- "
.SH DESCRIPTION
.B "Spushmeta is a SRB Admininstration utility for ingesting core MCAT system metadata for synchronizing metadata from one zone to another. The utility ingests metadata about zones, tokens used by the SRB such as the Data Types, User Type, etc, and also metadata about primary entities such as users, resources, collections, containers and data objects. The utilty can be used only with SRB Admin privelege. "
.sp
.B The 
.IR inputMetadatFile 
.B "is a file in the format as defined below. Spullmeta generates metadata file in this format. If the - option is used instead, the utility reads the file from stdin."
.sp
    COMMANDSTATEMENT
    ATTRIBUTELIST
    data (one row per line and values separated by a |)
    data 
    ... 
.sp

.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-h "
display command options
.PP
.SH "SEE ALSO"
.BR Spullmeta (1),
.BR Szone (1)
