.\" For ascii version, process this file with
.\" groff -man -Tascii Sattrs.1
.\"
.TH Sattrs 1 "Jan 2002 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Sattrs \- lists the queriable MCAT attributes.
.SH SYNOPSIS
.B Sattrs
.SH DESCRIPTION
.B "Sattrs "
lists the set of queriable MCAT attributes used
in conditions for choosing SRB objects.
.SH "SEE ALSO"
.BR Sls (1),
.BR Scat (1)
