.\" For ascii version, process this file with
.\" groff -man -Tascii Schdefres.1
.\"
.TH Schdefres 1 "Jan 2002 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Schdefres \- change default resource for the current session at the terminal. 
.SH SYNOPSIS
.B Schdefres
.I resourceName
.SH DESCRIPTION
.B "Schdefres "
changes the default resource used in commands such as Sput, Sbload, etc.

.sp
Note that reissuing an Sinit command will revert back to the default resource in .MdasEnv file.
Sessions in other terminals are not affected.
.PP
.SH "OPTIONS"
none
.SH "SEE ALSO"
.BR Sinit (1),
.BR Senv(1)
.BR Schhost(1)
.BR Sput(1)

