#!/bin/bash
################################################################################
## srb-failover-daemon
##   by Roman Olschanowsky 2004
##
##   SRB Failover daemon engine
################################################################################
SLEEP=300

echo $$ > run.pid

while [ `ps h -o sz -C srb-failover-daemon | tail -1` -lt 5000 ]
do
  ./srb-failover.php > DEBUG
  sleep $SLEEP
done
