#!/bin/csh
source ~/.cshrc
#setenv mdasEnvFile ''
#setenv mdasAuthFile ''
#set store1 = new-rep-test
#set storeset = (unix-sdsc illustra-sdsc hpss-sdsc db2-sdsc hpss-sdsc-nr db2-sdsc-nr unix-sdsc-nr illustra-sdsc-nr )
#set store1 = unix-sdsc
#set storeset = (PatAppArchive  PatAppArchive2 PatAppArchive3 PatAppArchive4)
#set store1 = unix-sdsc
#set storeset = (illustra-sdsc hpss-sdsc db2-sdsc)
set store1 = unix-sdsc
set storeset = (unix-sdsc ora-sdsc hpss-sdsc)

echo Performing Sinit
Sinit
echo Performing Senv
Senv
echo Performing Smkdir StestDir
Smkdir StestDir
echo Performing Scd StestDir
Scd StestDir
echo Performing Smkdir Ssub1
Smkdir Ssub1
echo Performing Sls
Sls -L 200 -r
echo Performing Scd Ssub1
Scd Ssub1
foreach file ( data* )
      echo Performing Sput -S $store1  $file "$file&COPIES=all"
      Sput -S $store1 $file "$file&COPIES=all" 
end
echo Performing Scd ..
Scd ..
echo Performing Sls
Sls -L 200 -r
foreach file ( data* )
      echo Performing Sget Ssub1/$file $file.tmp
      Sget Ssub1/$file $file.tmp
      echo Performing diff wc rm for $file.tmp
      diff $file $file.tmp
      wc $file $file.tmp
      rm $file.tmp
    endif  
end
echo Performing Smkdir Ssub2
Smkdir Ssub2
# Smv does not behave as mv
foreach file ( data* )
#     echo Performing Smv Ssub1/$file Ssub2
      echo Performing Scp Ssub1/$file Ssub2
#     Smv Ssub1/$file Ssub2
      Scp Ssub1/$file Ssub2
      Srm Ssub1/$file 

    endif  
end
echo Performing Sls
Sls  -L 200 -r
foreach store ( $storeset)
  foreach file ( data* )
       echo Performing Scp -S $store Ssub2/$file Ssub1/$file.$store
       Scp -S $store Ssub2/$file Ssub1/$file.$store
    endif  
  end
  echo Performing Sls
  Sls -r
  foreach file ( data* )
      echo Performing Sget Ssub1/$file.$store $file.tmp
      Sget Ssub1/$file.$store $file.tmp
      echo Performing diff wc rm for $file.tmp
      diff $file $file.tmp
      wc $file $file.tmp
      rm $file.tmp
    endif  
  end
end
echo Performing SgetD 
SgetD  -L 200 'Ssub1/*'
SgetD  -L 200 'Ssub2/*'
#Cleaning Up
echo Performing Scd
Scd
echo Performing Scd StestDir
Scd StestDir
echo Performing Scd Ssub1
Scd Ssub1
echo Performing Srm 'data*'
Srm 'data*'
echo Performing Scd ..
Scd ..
echo Performing Srm -r Ssub1
Srm -r Ssub1
echo Performing Sls
Sls  -L 200 -r
echo Performing Scd Ssub2
Scd Ssub2
echo Performing Srm 'data*'
Srm 'data*'
echo Performing Scd ..
Scd ..
echo Performing Srm -r Ssub2
Srmdir Ssub2
echo Performing Scd ..
Scd ..
echo Performing Srm -r StestDir
Srm -r StestDir
echo Performing Sexit
Sexit
