/*
 * MyProxyGUI.java
 *
 * Created on 27 March 2003, 12:21
 */
package uk.ac.dl.myproxy;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.util.*;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import org.gridforum.jgss.*;
import org.ietf.jgss.*;
import java.awt.event.*;
import java.net.*;
import org.globus.gsi.*;
import org.globus.gsi.gssapi.*;
import org.globus.common.CoGProperties;
import java.security.cert.*;
import org.globus.gsi.bc.*;
import java.security.PrivateKey;
/**
 *
 * @author  gjd37
 */
public class MyProxyGUI extends javax.swing.JDialog {
    MyProxyInsert my;
    String servername = "";
    String serverdn = "";
    int portnumber = 7512;
    String gridpassphrase = "";
    //int portallifetime= 2;
    int credentiallifetime= 168; //604800secs = 7days
    int portallifetime = 2;
    
    boolean isSetFields = true;
    
    
    String username = "";
    String password = "";
    
    private boolean closeOnSuccess = false;
    /** Creates new form MyProxyGUI */
   /* public MyProxyGUI(javax.swing.JFrame  parent, boolean modal, boolean show) {
        super(parent, modal);
        
        readInMyProxyConfig();
        
        initComponents();
        setTextFields();
        
        if(show && isSetFields) jButton8.doClick();
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        proxyproperties = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("MyProxy Configuration");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        getContentPane().add(jTextField1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        getContentPane().add(jTextField2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        getContentPane().add(jTextField3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        getContentPane().add(jTextField5, gridBagConstraints);

        jLabel1.setText("MyProxy Server");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 7);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("MyProxy Server DN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("MyProxy Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel5.setText("Credential Lifetime (hours)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel5, gridBagConstraints);

        jButton6.setMnemonic('c');
        jButton6.setText("Cancel");
        jButton6.setToolTipText("Exit the program");
        jButton6.setNextFocusableComponent(jButton8);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        getContentPane().add(jButton6, gridBagConstraints);

        jButton8.setMnemonic('s');
        jButton8.setText("Send");
        jButton8.setToolTipText("Set password for the MyProxy server");
        jButton8.setNextFocusableComponent(jButton6);
        jButton8.setSelected(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 2.0;
        getContentPane().add(jButton8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        getContentPane().add(jLabel10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 18);
        getContentPane().add(jLabel15, gridBagConstraints);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        getContentPane().add(jTextField4, gridBagConstraints);

        jLabel4.setText("Maximum Proxy Lifetime (hours)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        getContentPane().add(jLabel4, gridBagConstraints);

        jMenu1.setMnemonic('f');
        jMenu1.setText("Config");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });

        proxyproperties.setText("Proxy Options");
        proxyproperties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxypropertiesActionPerformed(evt);
            }
        });

        jMenu1.add(proxyproperties);

        jMenuItem1.setMnemonic('u');
        jMenuItem1.setText("Set username and password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-470)/2, (screenSize.height-213)/2, 470, 213);
    }//GEN-END:initComponents

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
       // File myproxy = new File(System.getProperty("user.home")+File.separator+".globus"+File.separator+"myproxy.properties");
      
        //if(!myproxy.exists()) proxyproperties.setEnabled(false);
    }//GEN-LAST:event_jMenu1MenuSelected
    
    private void proxypropertiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxypropertiesActionPerformed
        // TODO add your handling code here:
  /*      MyProxyCredentialsProperties mpcp = new MyProxyCredentialsProperties(this, true);
        mpcp.setResizable(false);
        
        //my.setBounds(x,y,w,h);
        mpcp.setLocationRelativeTo(this);
        
        mpcp.setVisible(true);*/
    }//GEN-LAST:event_proxypropertiesActionPerformed
    
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Add your handling code here:
        openMyProxyInsert();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // Add your handling code here:
        // Add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //try to send to myproxy
        openMyProxyInsert();
        
        
    }//GEN-LAST:event_jButton8ActionPerformed
    private void putIntoMyProxy() {
        
        final JLabel msgLabel = new JLabel("Sending proxy...");
        final JProgressBar progressBar = new JProgressBar(0, 10);
        
        progressBar.setValue(0);
        
        Object [] comp = {msgLabel, progressBar};
        Object [] options = { "Cancel" };
        
        JOptionPane pane = new JOptionPane(comp,
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.INFORMATION_MESSAGE,
        null,
        options,
        options[0]);
        
        final JDialog dialog = pane.createDialog(this, "Contacting MyProxy Server..");
        
        final Task task = new Task();
        
        Timer timer = new Timer(250, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (task.isDone()) {
                    dialog.setVisible(false);
                } else {
                    progressBar.setValue( (progressBar.getValue()+1) % 10 );
                }
            }
        });
        
        timer.start();
        task.start();
        
        try { Thread.sleep(500); } catch(Exception e) {}
        
        Object selectedValue = null;
        
        if (task.getException() == null) {
            
            dialog.show();
            selectedValue = pane.getValue();
        } else {
            selectedValue = JOptionPane.UNINITIALIZED_VALUE;
        }
        
        timer.stop();
        
        if (selectedValue == null || selectedValue == options[0]) {
            // window closed by user or cancel pressed
            task.cancel(); // <-- this does not work!!!!
            //proxy = null;
        } else if (selectedValue == JOptionPane.UNINITIALIZED_VALUE) {
            // task finished
            Throwable e = task.getException();
            //System.out.println(e.getMessage());
            if (e == null) {
                
                //proxy = task.getProxy();
                JOptionPane.showMessageDialog(this,
                "Proxy was successfully uploaded.",
                "Proxy upload",
                JOptionPane.INFORMATION_MESSAGE);
                
                if (closeOnSuccess){
                    
                    
                    System.exit(-1);
                    setVisible(false);
                    
                }
                System.exit(-1);
                setVisible(false);
            }
            //For the web start.  Current version of Cog Kit 1.1 with jce-jdk117.jar.  jce-jdk117.jar has been
            // signed by the wrong JCE private key and therefore web start will not allow it to be downloaded
            // (any webstart with jdk 1.4 wont, i think 1.3 will) So web start version does not come with
            // bouncy castle jar files.  This needs to be downloaded seperatley.  So so this error.
            else if(e instanceof NoClassDefFoundError){
                JOptionPane.showMessageDialog(this,e.getMessage()+"\nMake sure you have downloaded the Bouncy Castle jar file.","Error",  JOptionPane.ERROR_MESSAGE);
                
            }
            //Current version of Cog Kit 1.1 with jce-jdk117.jar throws this error on certain OS.  Not sure why.
            //Show error and explain to the user
            else if(e.getMessage().startsWith("org.bouncycastle.asn1.x509.X509Extension.getValue()") || e instanceof java.lang.NoSuchMethodError ){
                
                //test if old jce in class path
                String java_home = System.getProperty("java.home");
                File jce = new File(java_home+File.separator+"lib"+File.separator+"ext"+File.separator+"jce-jdk13-117.jar");
                File jce2 = new File(java_home+"jre"+File.separator+"lib"+File.separator+"lib"+File.separator+"ext"+File.separator+"jce-jdk13-117.jar");
                
                if(jce.exists()){
                    JOptionPane.showMessageDialog(this,
                    "You have an old version of the jce security classes in your java classpath.\nPlease remove "+jce.getAbsolutePath()+"\nAll java applications need to be closed before it can be removed.",
                    "Data Portal Proxy Error",
                    JOptionPane.ERROR_MESSAGE);
                    
                }
                else if(jce2.exists()){
                    JOptionPane.showMessageDialog(this,
                    "You have an old version of the jce security classes in you class path.\nPlease remove "+jce2.getAbsolutePath()+"\nAll java applications need to be closed before it can be removed",
                    "Data Portal Proxy Error",
                    JOptionPane.ERROR_MESSAGE);
                    
                }
                else{
                    JOptionPane.showMessageDialog(this,
                    "The Java Cog Kit used with the Data Portal Proxy does not fully support this Operating System.\nSending your credentials into the MyProxy Server does not work.\nPlease try the Data Portal Proxy with another OS.",
                    "Data Portal Proxy Error",
                    JOptionPane.ERROR_MESSAGE);
                }
            }
            else if(e instanceof javax.crypto.BadPaddingException){
                JOptionPane.showMessageDialog(this,
                "Failed to send proxy: " + e.getMessage()+"\nIs your Grid PassPhrase correct?",
                "Proxy send Error",
                JOptionPane.ERROR_MESSAGE);
                my.setVisible(true);
            }
            //anything else show error.
            else {
                
                //proxy = null;
                JOptionPane.showMessageDialog(this,
                "Failed to send proxy: " + e.getMessage(),
                "Proxy send Error",
                JOptionPane.ERROR_MESSAGE);
                my.setVisible(true);
            }
        } else {
            //proxy = null;
        }
        
    }
    
    class Task extends Thread {
        private boolean done = false;
        private Throwable exception = null;
        private boolean cancel = false;
        //private GlobusCredential proxy = null;
        
        public boolean isDone() {
            return done;
        }
        
        public void cancel() {
            cancel = true;
        }
        
        public boolean isCancelled() {
            return cancel;
        }
        public Throwable getException() {
            return exception;
        }
        
        
        public void run() {
            try{
                /// New section to put into myproxy
                org.globus.myproxy.MyProxy proxy1 = new  org.globus.myproxy.MyProxy(servername,portnumber);
                CoGProperties properties = CoGProperties.getDefault();
                String usercert= properties.getUserCertFile();
                String userkey= properties.getUserKeyFile();
                
                //gte users X059 cert and privaye key
                X509Certificate X509Cert = CertUtil.loadCertificate(usercert);
                OpenSSLKey key = new BouncyCastleOpenSSLKey( userkey );
                key.decrypt( gridpassphrase );
                PrivateKey issuerKey = key.getPrivateKey();
                
                //create proxy credential
                BouncyCastleCertProcessingFactory certFactory = BouncyCastleCertProcessingFactory.getDefault();
                GlobusCredential delegateCred  = certFactory.createCredential( new X509Certificate[] { X509Cert},issuerKey,512, credentiallifetime*3600, GSIConstants.DELEGATION_FULL );
                GSSCredential cred = new GlobusGSSCredentialImpl(delegateCred, GSSCredential.INITIATE_AND_ACCEPT);
                
                System.out.println("Created Proxy Credential");
                System.out.println("Credential info:");
                System.out.println("Subject : "+cred.getName());
                System.out.println("LifeTime : "+cred.getRemainingLifetime());
                
                //when putting it into MyProxy, specify that maximum time that the proxy can be
                //taken out for.  IE 2 hours.
                proxy1.put(cred, username, password, portallifetime*3600);
                
                done= true;
                //end of new section
                
                
                
             /*   org.globus.myproxy.MyProxy proxy1 = new  org.globus.myproxy.MyProxy(servername,portnumber);
                //ExtendedGSSManager manager = (ExtendedGSSManager)ExtendedGSSManager.getInstance();
                //GSSCredential cred = manager.createCredential(GSSCredential.INITIATE_AND_ACCEPT);
                //GSSCredential cred = org.globus.tools.MyProxy.createNewProxy(7200,"k4te£1t$");
                org.globus.tools.proxy.DefaultGridProxyModel p = new org.globus.tools.proxy.DefaultGridProxyModel();
                //create a proxy for normally 168 hours (7 days) and put that into myproxy
                // this is the lifetime that the proxy is valid for in the myProxy server
                GlobusCredential cred  = p.createProxy(gridpassphrase,credentiallifetime*3600);
                //cred.save(new FileOutputStream("c:/finally1.pem"));
                GSSCredential cred2 = new GlobusGSSCredentialImpl(cred, GSSCredential.INITIATE_AND_ACCEPT);
                //when putting it into MyProxy, specify that maximum time that the proxy can be
                //taken out for.  IE 2 hours.
                proxy1.put(cred2, username, password, 2*3600);*/
                
                //done= true;
            }
            catch(NoClassDefFoundError b){
                b.printStackTrace();
                done= true;
                
                exception =  b;
            }
            catch(Throwable e){
                System.out.println(e);
                done= true;
                exception =  e;
                
            }
        }
        
        
    }
    
    
    private void save() throws Exception{
        
        getText();
        
        File myproxy = new File(System.getProperty("user.home")+File.separator+".globus"+File.separator+"myproxy.properties");
        
        try{
            if(!myproxy.isFile()) myproxy.createNewFile();
            Properties prop = new Properties();
            prop.load(new FileInputStream(myproxy));
            prop.setProperty("servername", servername);
            prop.setProperty("serverdn",serverdn);
            if(servername.equals("")){
                throw new Exception("MyProxy Server cannot be empty");
            }
            else if(serverdn.equals("")){
                throw new Exception("MyProxy Server DN cannot be empty");
            }
            
            prop.setProperty("portnumber",String.valueOf(portnumber));
            //prop.setProperty("portallifetime",String.valueOf(portallifetime));
            prop.setProperty("credentiallifetime",String.valueOf(credentiallifetime));
            prop.setProperty("portallifetime",String.valueOf(portallifetime));
            FileOutputStream out = new FileOutputStream(myproxy);
            prop.store(out,"Myproxy");
            out.close();
            // JOptionPane.showMessageDialog(this,"Config saved","Message" ,  JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch(Exception e){
            //JOptionPane.showMessageDialog(this,new String(e.toString()),"Error" ,  JOptionPane.ERROR_MESSAGE);
            throw e;
        }
        
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Add your handling code here:
        //System.exit(-1);
        //save();
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Add your handling code here:
        System.out.println("open box");
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    
    
    public void getText() throws NumberFormatException{
        servername =    jTextField1.getText().trim();
        serverdn =  jTextField2.getText().trim();
        portnumber  = Integer.parseInt(jTextField3.getText().trim());
        //portallifetime = Integer.parseInt(jTextField4.getText());
        credentiallifetime =  Integer.parseInt(jTextField5.getText().trim());
        portallifetime =  Integer.parseInt(jTextField4.getText().trim());
        
    }
   // public String getUsername(){
       // return my.getUsername();
        
   // }
    
  //  public String getPassword(){
  //     // return my.getPassword();
        
  /*  }
    public void readInMyProxyConfig(){
        
        File myproxy = new File(System.getProperty("user.home")+File.separator+".globus"+File.separator+"myproxy.properties");
        if(!myproxy.exists()){
            isSetFields = false;
        }
        else{
            try{
                Properties prop = new Properties();
                prop.load(new FileInputStream(myproxy));
                
                servername = prop.getProperty("servername");
                serverdn =prop.getProperty("serverdn");
                if(servername==null || serverdn==null || servername.equals("") || serverdn.equals("")) isSetFields = false;
                portnumber = Integer.parseInt(prop.getProperty("portnumber","7512"));
                // portallifetime= Integer.parseInt(prop.getProperty("portallifetime"));
                credentiallifetime= Integer.parseInt(prop.getProperty("credentiallifetime","168"));
                portallifetime = Integer.parseInt(prop.getProperty("portallifetime","2"));
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,"Unable to read config file. \n"+new String(e.toString()),"Error" ,  JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
        
        
    }*/
    public void setTextFields(){
        jTextField1.setText(servername);
        jTextField2.setText(serverdn);
        jTextField3.setText(String.valueOf(portnumber));
        jTextField4.setText(String.valueOf(portallifetime));
        
        jTextField5.setText(String.valueOf(credentiallifetime));
        
    }
    
    public void openMyProxyInsert(){
       /* my  = new MyProxyInsert(null,true);
        my.setResizable(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = 300;
        int h = 150;
        int x = (dim.width -w)/2;
        int y = (dim.height -h)/2;
        my.setBounds(x,y,w,h);
        my.setVisible(true);
        */
        
        
        //try to send to myproxy
    /*    try{
            save();
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,e.toString(),"Error" ,  JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.toString(),"Error" ,  JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        
        if(my == null) {
            //JOptionPane.showMessageDialog(this,"Please enter an username and password \n Use the Config menu","Error" ,  JOptionPane.ERROR_MESSAGE);
            my  = new MyProxyInsert(this,true);
            my.setResizable(true);
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            int w = 300;
            int h = 150;
            int x = (dim.width -w)/2;
            int y = (dim.height -h)/2;
            //my.setBounds(x,y,w,h);
            my.setLocationRelativeTo(this);
            
            my.setVisible(true);
            // putIntoMyProxy();
            //return;
            username =  my.getUsername();
            password = my.getPassword();
            gridpassphrase = my.getGridPassword();
            if(username.equals("") ||password.equals("")|| gridpassphrase.equals("")) return;
        }
        else{
            my.setLocationRelativeTo(this);
            my.setVisible(true);
            username =  my.getUsername();
            password = my.getPassword();
            
            gridpassphrase = my.getGridPassword();
            if(username.equals("") ||password.equals("")|| gridpassphrase.equals("")) return;
        }
        
        
        try{
            //org.globus.myproxy.MyProxy proxy1 = new  org.globus.myproxy.MyProxy(servername,portnumber);
            //ExtendedGSSManager manager = (ExtendedGSSManager)ExtendedGSSManager.getInstance();
            //GSSCredential cred = manager.createCredential(GSSCredential.INITIATE_AND_ACCEPT);
            //proxy1.put(cred, username, password, portallifetime);
            // JOptionPane.showMessageDialog(this,"Credentials send to MyProxy","Message" ,  JOptionPane.INFORMATION_MESSAGE);
            putIntoMyProxy();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.toString(),"Error" ,  JOptionPane.ERROR_MESSAGE);
            my.setLocationRelativeTo(this);
            my.setVisible(true);
            
        }*/
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JMenuItem proxyproperties;
    // End of variables declaration//GEN-END:variables
    
}
