.\" For ascii version, process this file with
.\" groff -man -Tascii tapemeta.1
.\"
.TH tapemeta 1 "Jan 2003 " "Storage Resource Broker" "Tape Admin Commands"
.SH NAME
tapemeta \- Modify the metadata of a tape that has been registeredf with MCAT.
.SH SYNOPSIS
.B tapemeta
.RB [ \-h ]
.RB [ \-n
.IR newTapeNum ]
.RB [ \-u
.IR tapeOwner ]
.RB [ \-t
.IR typeType ]
.RB [ \-l
.IR tapeLibInx ]
.RB [ \-f
.IR fullFlag ]
.RB [ \-s
.IR curFileSeqNum ]
.RB [ \-p
.IR curAbsPos ]
.RB [ \-b
.IR bytesWritten ]
.I tapeNum
.SH DESCRIPTION
.B "Tapemeta "
is a sys admin utility that modifies the meta data of a tape that has been registered with MCAT.
.B TapeNum
specifies the tape whose meta data is to be modified.
.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-h "
display command options
.TP 0.5i
.B "\-n "
.I newTapeNum
specifies the new value for tapeNum.
.TP 0.5i
.B "\-u "
.I tapeOwner
specifies the new value for tapeOwner.
.TP 0.5i
.B "\-t "
.I tapeType
specifies the new value for tapeType.
.TP 0.5i
.B "\-l "
.I tapeLibInx
specifies the new value for tapeLibInx.
.TP 0.5i
.B "\-f "
.I fullFlag
specifies the new value for fullFlag.
.TP 0.5i
.B "\-s "
.I curFileSeqNum
specifies the new value for curFileSeqNum.
.TP 0.5i
.B "\-p "
.I curAbsPos
specifies the new value for curAbsPos.
.TP 0.5i
.B "\-b "
.I bytesWritten
specifies the new value for bytesWritten.
.SH "SEE ALSO"
.BR dumptape (1),
.BR lstape (1),
.BR inittape (1)

