.\" For ascii version, process this file with
.\" groff -man -Tascii lstape.1
.\"
.TH lstape 1 "Jan 2003 " "Storage Resource Broker" "Tape Admin Commands"
.SH NAME
lstape \- List the tapes and their associated meta data in MCAT
.SH SYNOPSIS
.B lstape
.RB [ \-hfn ]
.RI [ tapeNumber " ...]"
.SH DESCRIPTION
.B "Lstape "
is a sys admin utility that list the tapes and their associated
meta data in MCAT. tapeNumber specfies the tape whose meta data
is to be listed. If no tapeNumber is specified, all tapes in
MCAT will be listed.
.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-h "
display command options
.TP 0.5i
.B "\-f "
list only tapes that are full.
.TP 0.5i
.B "\-n "
list only tapes that are not full.
.TP 0.5i
.B "\-R "
tape registration only
.TP 0.5i
.B "\-L "
tape labelling only
.SH "SEE ALSO"
.BR dumptape (1),
.BR inittape (1),
.BR tapemeta (1)

