.\" For ascii version, process this file with
.\" groff -man -Tascii Schhost.1
.\"
.TH Schhost 1 "Jan 2002 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Schhost \- change default connection host for the current session at the terminal.  
.SH SYNOPSIS
.B Schhost
.I hostName
.SH DESCRIPTION
.B "Schhost "
changes the connecting server host name.
.sp
Note that reissuing an Sinit command will revert back to the host  in .MdasEnv file.
Sessions in other terminals are not affected.
.PP
.SH "OPTIONS"
none
.SH "SEE ALSO"
.BR Sinit (1),
.BR Senv(1)
.BR Schdefres(1)

