.\" For ascii version, process this file with
.\" groff -man -Tascii Sinit.1
.\"
.TH Sinit 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Sinit \- initializes SRB client environment.
.SH SYNOPSIS
.B Sinit
.RB [ \-v ]
.SH DESCRIPTION
.B "Sinit "
initializes the client environment session by making
a copy for this session from the orignal Client
Environment file. The Client Environment file is
normally located in ~/.srb/.MdasEnv.
.sp
The name of the session Client Environment file is
based on the parent's (possibly shell) process identifier
.sp
Sinit allows more than one parallel session to be
manintained from a user's account. (usually through
separate shells)
.sp
Sinit should be the first SRB command to be given before
invoking any other S-commands. Otherwise error 1200
(UTIL_ERROR_ENV_FILE_OPEN) will result.
.sp
Recommended to have it as part of login script.
.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-v "
Display the client and server release versions. The
output gives a "release  version" and an "API version".
A client may communication with servers with
different "release versions", but they must have the
same "API version".
.SH "SEE ALSO"
.BR Sexit (1),
.BR Senv (1)
