.\" For ascii version, process this file with
.\" groff -man -Tascii Spwd.1
.\"
.TH Spwd 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Spwd \- displays current working SRB collection
.SH SYNOPSIS
.B Spwd
.SH DESCRIPTION
.B "Spwd "
displays the current working SRB collection.
.SH "OPTIONS"
none
.SH "SEE ALSO"
.BR Scd (1)


