.\" For ascii version, process this file with
.\" groff -man -Tascii SmodColl.1
.\"
.TH SmodColl 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
SmodColl \- modifies metadata information about a SRB collection.
.SH SYNOPSIS
.B SmodColl
.RB [ \-dh ] " \-c"
.I container collection
.SH DESCRIPTION
.B "SmodColl "
modifies metadata information about the given
.IR collection . 
Currently, only the container metadata can be modified with this command. The -c option is used to associate a container with the collection. If the \-d option is not used, the association is added to the metadata. If the \-d option is used, the association is deleted from the metadata.
.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-h "
display command options
.TP 0.5i
.B "\-d "
delete
.TP 0.5i
.B "\-c " container 
container to be associated with the collection.
.SH "SEE ALSO"
.BR SgetD (1),
.BR Smkdir (1),
.BR Sls (1)

