.\" For ascii version, process this file with
.\" groff -man -Tascii Sreplcont.1
.\"
.TH Sreplcont 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Sreplcont \- Replicate a container copy.
.SH SYNOPSIS
.B Sreplcont
.RB [ \-z
.IR mcatZone ]
.RB [ \-S
.IR resource "] " container
.SH DESCRIPTION
.B "Sreplcont "
Replicates a container copy to a specific resource. For containers
that have multiple "permanent" and "cache" copies, this is a way
to put a copy of the container on a specific resource. For
example, if a container was created in multiple "cache" resources,
this is a way to stage this container on a "cache" resource that
is not designated as "primary". 
.PP
The specified destination
.I resource
must be a "cache" class resource or
belong to one of the physical resources of the
container's logical resource if it is an "archival" class resource.
.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-h "
display command options
.TP 0.5i
.B "\-z mcatZone "
The MCAT zone where the container resides
.TP 0.5i
.B "\-S "
.I resource
the resource where the container copy is to be created.
.SH "SEE ALSO"
.BR Srmcont (1),
.BR Smkcont (1),
.BR Slscont (1),
.BR Ssyncont (1)

