.\" For ascii version, process this file with
.\" groff -man -Tascii Srmdir.1
.\"
.TH Srmdir 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Srmdir \- deletes a SRB collection
.SH SYNOPSIS
.B Srmdir
.I collection
.SH DESCRIPTION
.B "Srmdir "
deletes an existing SRB collection.
.PP
.SH "OPTIONS"
none
.SH "SEE ALSO"
.BR Spwd (1),
.BR Scd (1),
.BR Sls (1),
.BR Smkdir (1)

