/*
 * PrintTest.java
 *
 * Created on 09 April 2001, 10:51
 */
import java.awt.*;
import java.awt.geom.*;
import java.awt.image.*;
import java.awt.print.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author  djn
 */
public class PrintTest extends javax.swing.JFrame implements Printable {

    int X=640, Y=512;
    
    class Java2DImage extends JPanel{
            public void paint( Graphics g ){
                final int X = getWidth();
                final int Y = getHeight();
                Graphics2D g2d = (Graphics2D)g;
                g2d.setRenderingHint( RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON );
                g2d.drawRect( -100, -100, 200, 200 );
                AffineTransform at = new AffineTransform();
                double alpha = Math.atan( (double)Y/X );
                at.setToRotation( alpha );
                g2d.setTransform( at );
                String s = "Testing...";
                int size = 12;
                Font f = new Font( "Serif", Font.BOLD, size );
                size *= Math.sqrt( X*X + Y*Y ) / g2d.getFontMetrics( f ).stringWidth( s );
                g2d.setFont( new Font( "Serif", Font.BOLD, size ) );
                g2d.setColor( Color.black );
                double height = g2d.getFontMetrics().getHeight();
                float x = (float)( height * Math.cos( alpha )/2 );
                float y = (float)( height * Math.sin( alpha )/2 );
                g2d.drawString( s, x, y );
        }
    };
    
    public int print( Graphics g, PageFormat pf, int pageIndex ){
        if ( pageIndex > 0 ){
            return Printable.NO_SUCH_PAGE;
        }
        Graphics2D g2d = (Graphics2D)g;
        g2d.translate( pf.getImageableX(), pf.getImageableY() );
        paint( g2d );
        return Printable.PAGE_EXISTS;
    }
      
    /** Creates new form PrintTest */
    public PrintTest() {
        initComponents();
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        label = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        panel = new PrintTest.Java2DImage();
        panel.setPreferredSize( new Dimension( X, Y ) );
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        label.setText("Printing test...");
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black, 4, true));
        getContentPane().add(label, java.awt.BorderLayout.NORTH);
        
        button.setText("Print");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printGUI(evt);
            }
        });
        
        getContentPane().add(button, java.awt.BorderLayout.SOUTH);
        
        getContentPane().add(panel, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    private void printGUI(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printGUI
        // Add your handling code here:
         System.out.println( "In printGUI()" );
        PrinterJob pjob = PrinterJob.getPrinterJob();
        PageFormat pf = pjob.defaultPage();
        pjob.setPrintable( this, pf );
        try{
            if ( pjob.printDialog() ){
                System.out.println( "Initiating print..." );
                pjob.print();
            } else {
                System.out.println( "No print" );
            }
        }
        catch( PrinterException pe ){
            JOptionPane.showMessageDialog( this, "Problem whilst printing...\n" + pe.toString()  );
            pe.printStackTrace();
        }
    }//GEN-LAST:event_printGUI

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new PrintTest().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JButton button;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

}
