//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.06.06 at 12:17:03 BST 
//


package edu.sdsc.matrix.srb.parser;


/**
 * Java content class for CopyParams complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="CopyParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSource" type="{http://www.teragrid.org/schemas/datagrid}StdDatagridObject"/>
 *         &lt;element name="DataTarget" type="{http://www.teragrid.org/schemas/datagrid}StdDatagridObject"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface CopyParams {


    edu.sdsc.matrix.srb.parser.StdDatagridObject getDataSource();

    void setDataSource(edu.sdsc.matrix.srb.parser.StdDatagridObject value);

    edu.sdsc.matrix.srb.parser.StdDatagridObject getDataTarget();

    void setDataTarget(edu.sdsc.matrix.srb.parser.StdDatagridObject value);

}
