//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.06.06 at 12:17:03 BST 
//


package edu.sdsc.matrix.srb.parser;


/**
 * Java content class for StdDatagridObject complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="StdDatagridObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="CollectionNow" type="{http://www.teragrid.org/schemas/datagrid}Collection"/>
 *         &lt;element name="DataSetNow" type="{http://www.teragrid.org/schemas/datagrid}DataSet"/>
 *         &lt;element name="ContainerNow" type="{http://www.teragrid.org/schemas/datagrid}Container"/>
 *         &lt;element name="ADCnow" type="{http://www.teragrid.org/schemas/datagrid}ActiveDatagridCollection"/>
 *         &lt;element name="ActiveDataSetNow" type="{http://www.teragrid.org/schemas/datagrid}ActiveDatagridDataSet"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface StdDatagridObject {


    edu.sdsc.matrix.srb.parser.DataSet getDataSetNow();

    void setDataSetNow(edu.sdsc.matrix.srb.parser.DataSet value);

    edu.sdsc.matrix.srb.parser.Collection getCollectionNow();

    void setCollectionNow(edu.sdsc.matrix.srb.parser.Collection value);

    edu.sdsc.matrix.srb.parser.Container getContainerNow();

    void setContainerNow(edu.sdsc.matrix.srb.parser.Container value);

    edu.sdsc.matrix.srb.parser.ActiveDatagridDataSet getActiveDataSetNow();

    void setActiveDataSetNow(edu.sdsc.matrix.srb.parser.ActiveDatagridDataSet value);

    edu.sdsc.matrix.srb.parser.ActiveDatagridCollection getADCnow();

    void setADCnow(edu.sdsc.matrix.srb.parser.ActiveDatagridCollection value);

}
