//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.06.06 at 12:17:03 BST 
//


package edu.sdsc.matrix.srb.parser;


/**
 * Java content class for ChangePermissionParams complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="ChangePermissionParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gridData" type="{http://www.teragrid.org/schemas/datagrid}StdDatagridObject"/>
 *         &lt;element name="targetUser" type="{http://www.teragrid.org/schemas/datagrid}UserInfo"/>
 *         &lt;element name="newPermission">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="read"/>
 *             &lt;enumeration value="write"/>
 *             &lt;enumeration value="all"/>
 *             &lt;enumeration value="annotate"/>
 *             &lt;enumeration value="none"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *         &lt;element name="recursive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="auditNewAccess" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="collectionOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dataSetOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ChangePermissionParams {


    edu.sdsc.matrix.srb.parser.AnyType getAuditNewAccess();

    void setAuditNewAccess(edu.sdsc.matrix.srb.parser.AnyType value);

    boolean isRecursive();

    void setRecursive(boolean value);

    boolean isCollectionOnly();

    void setCollectionOnly(boolean value);

    edu.sdsc.matrix.srb.parser.UserInfo getTargetUser();

    void setTargetUser(edu.sdsc.matrix.srb.parser.UserInfo value);

    boolean isDataSetOnly();

    void setDataSetOnly(boolean value);

    edu.sdsc.matrix.srb.parser.StdDatagridObject getGridData();

    void setGridData(edu.sdsc.matrix.srb.parser.StdDatagridObject value);

    java.lang.String getNewPermission();

    void setNewPermission(java.lang.String value);

}
