#!/bin/bash

# to run this do 
# . create_cp
# in the directory where the jar files are e.g. dataportal/<module>/build/WEB-INF/lib
# useful for creating classpath for test scripts which need jars that the servlets need

export CLASSPATH=.

for i in `ls *.jar`
do
export CLASSPATH=$CLASSPATH:`pwd`\/$i
done

#following needed for axis test programs

export CLASSPATH=$CLASSPATH:$CATALINA_HOME/common/lib/servlet.jar

echo $CLASSPATH


