#!/bin/sh
#
# helpsuite
#
# Typical invocation:
#	helpsuite > help.log

# Note: needs translation to perl for NT


######## clConnect ##########

bin/srbhello -help
echo ""

bin/srbchkauth -help
echo ""

bin/srbhostinfo -help
echo ""

bin/srbvaultinfo -help
echo ""


######## audit trail ##########

bin/srbaudittrail -help
echo ""

######### srb "ftp" #########

bin/srbftpbrowse -help
echo ""


########## srbFile ##########

bin/srblsdir -help
echo ""

bin/srbmkdir -help
echo ""

bin/srbrmdir -help
echo ""

bin/srbfcreate -help
echo ""

bin/srbfchmod -help
echo ""

bin/srbfstat -help
echo ""

bin/srbfget -help
echo ""

bin/srbfseek -help
echo ""

bin/srbfdel -help
echo ""


########## srbObj ##########

bin/srbmkcoll -help
echo ""

bin/srblscoll -help
echo ""

bin/srbmodcoll -help
echo ""

bin/srbocreate -help
echo ""

bin/srbodsinfo -help
echo ""

bin/srboddinfo -help
echo ""

bin/srboget -help
echo ""

bin/srboseek -help
echo ""

bin/srbomove -help
echo ""

bin/srbocopy -help
echo ""

bin/srbodel -help
echo ""


########## db large object ##########


bin/srbdbcreate -help
echo ""

bin/srbdbget -help
echo ""

bin/srbdbseek -help
echo ""

bin/srbdbdel -help
echo ""

