/* Generated By:JJTree: Do not edit this line. ASTNotSupported.java */

package edu.sdsc.matrix.srb.query;

/*
 * 
 * @author rmathew
 *
 * Class used for query parsing
 * To Help in processing Query Clauses not supported
 */

public class ASTNotSupported extends SimpleNode {
  public ASTNotSupported(int id) {
    super(id);
  }

  public ASTNotSupported(MatrixQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MatrixQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
