.\" For ascii version, process this file with
.\" groff -man -Tascii Senv.1
.\"
.TH Senv 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Senv \- Displays SRB environmental file content
.SH SYNOPSIS
.B Senv
.SH DESCRIPTION
.B "Senv "
routine reads the current SRB session connection parameters
and displays them.
.sp
SRB Connection parameters are usually set from the .MdasEnv file.
But can also be set using environment variables.
.PP
.SH "OPTIONS"
none
.SH "SEE ALSO"
.BR Sinit (1),
.BR Sexit (1)


