.\" For ascii version, process this file with
.\" groff -man -Tascii S.1
.\"
.TH Singestuser 1 "April 2004 " "Storage Resource Broker" "Admin SRB Commands"
.SH NAME
Singestuser \- adds an account to a SRB grid.
.SH SYNOPSIS
.B Singestuser
.I NewUserName NewUserPassword NewUserDomain NewUserType NewUserAddress NewUserPhone NewUserEmail NewUserAuthScheme NewUserDNString
.SH DESCRIPTION
.B "Singestuser "
adds an account to a SRB grid. Be careful to quote fields with spaces.
.PP
.SH "FIELDS"
.TP 0.5i
.B "NewUserName "
the name for the account
.TP 0.5i
.B "NewUserPassword "
the account password
.TP 0.5i
.B "NewUserDomain "
the domain of the account
.TP 0.5i
.B "NewUserType "
the type of account (staff, sysadmin, etc...) use "Stoken UserType"
.TP 0.5i
.B "NewUserAddress "
the address of the user
.TP 0.5i
.B "NewUserPhone "
the phone number of the user
.TP 0.5i
.B "NewUserEmail "
the email of the user
.TP 0.5i
.B "NewUserAuthScheme "
how the user will be authenticated (ENCRYPT1, GSI_AUTH, etc...) (by default not enforced)
.TP 0.5i
.B "NewUserDNString "
Distinguished Name for GSI authentication
.SH "SEE ALSO"
.BR SmodifyUser (1),
.BR SgetU (1),
.BR Stoken (1)
