.\" For ascii version, process this file with
.\" groff -man -Tascii Sappend.1
.\"
.TH Sappend 1 "Jan 2002 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Sappend \- appends a local file or a SRB object to a target SRB object.
.SH SYNOPSIS
.B Sappend
.I localFileName srbTarget
.br
.B Sappend \-i
.I srbTarget
.br
.B Sappend \-s
.I srbObj srbTarget
.SH DESCRIPTION
In the first synopsis,
.B Sappend
appends a local file
.I localFileName
to an existing SRB object
.IR srbTarget .
The user should have at least read permission for
.I localFileName
and at least 'write' permission for 
.IR srbTarget .
.sp
In  the  second  synopsis, the appended file is taken from the
standard input.
.sp
In the third synopsis, 
.B Sappend
appends an existing SRB object to another SRB object. The user
should have at least read permission for
.I srbObj
and at least 'write' permission for
.IR srbTarget .
If
.I srbObj
is replicated then one of the copies is read.
.sp
The
.IR srbObj and srbTarget
arguments can be path names in the SRB collection hierarchy.
.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-h "
displays command options
.TP 0.5i
.B "\-i "
appended from standard input
.TP 0.5i
.B "\-s "
append existing SRB object to another SRB object
.SH "SEE ALSO"
.BR Sput (1)

