.\" For ascii version, process this file with
.\" groff -man -Tascii Srmcont.1
.\"
.TH Srmcont 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Srmcont \- Remove a SRB container
.SH SYNOPSIS
.B Srmcont
.RB [ \-afh ]
.RB [ \-z
.IR mcatZone ]
.I container
.SH DESCRIPTION
.B "Srmcont "
removes an existing SRB container. The container must be empty
(free of inContainer objects) before it can be removed.
.sp
The
.I container
may be an absolute path or a relative path in the SRB name space.
If the path is relative, the container is assumed to be in the
user's container collection path - /container/userName.domainName.
.sp
When a container is full, the SRB server automatically renames the full container "myContainer" to "myContainer.NNNN" where NNNN is a random integer number. 
The server then creates an empty container with the original container name "myContainer". In effect, this scheme creates a family of containers. 
The -a option can be used to delete all containers in a family.
.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-a "
delete all containers in a container family.
.TP 0.5i
.B "\-h "
display command options
.TP 0.5i
.B "\-f "
Force the removal of all inContainer objects stored in this
container before removing the container.
.TP 0.5i
.B "\-z mcatZone "
The MCAT zone where the container resides
.SH "SEE ALSO"
.BR Smkcont (1),
.BR Slscont (1)

