.\" For ascii version, process this file with
.\" groff -man -Tascii Ssyncd.1
.\"
.TH Ssyncd 1 "Jan 2003 " "Storage Resource Broker" "User SRB Commands"
.SH NAME
Ssyncd \- synchronizes copies of an SRB object
.SH SYNOPSIS
.B Ssyncd
.RB [ \-ar "] [" \-S
.IR resourceName "] " srbObj | collection " ..."
.SH DESCRIPTION
.B "Ssyncd "
synchronizes all copies (replica) of an SRB object with the most
recently modified (dirty) copy. 
.sp
If the 
.IR resourceName 
is given using the -S option, in addition to synchronizing to all
existing copies, a copy will be made in the specified resource if a
copy does not already exist in the resource.
.sp
If the 
.IR resourceName 
is a logical resource consisting of multiple resources, only one copy
will be made to one of the resources in the group. The -a option can
be used to make a copy in each resources in the group.
.sp
For synchronizing collections, the recursive option (r) must be set.
.sp
The
.IR srbObj " or " collection
arguments can be path names in the SRB collection hierarchy.
.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-a "
If the target resource is a logical resource consisting of more than
one resources, then make a copy in each resources in the group.
.TP 0.5i
.B "\-r "
recursively synchronizing the collection.
.TP 0.5i
.B "\-S "
.I "resourceName "
is the target resourceName.
.SH "SEE ALSO"
.BR Sreplicate (1),
.BR Sphymove (1),
.BR Smv (1),
.BR Scp (1)

