/*
 * TestICATSingleton.java
 * JUnit based test
 *
 * Created on 25 June 2007, 11:23
 */

package uk.ac.dp.icatws;


import javax.xml.ws.BindingProvider;
import junit.framework.JUnit4TestAdapter;
import static org.junit.Assert.*;
import org.junit.Test;
/**
 *
 * @author gjd37
 */
public class TestICATSingleton  {
    
    
    
    protected void setUp() throws Exception {
    }
    
    protected void tearDown() throws Exception {
    }
    
    // @Test()
    public void atest1(){
        System.out.println("testing speed");
        long time = System.currentTimeMillis();
        ICATService icatService = new ICATService();
        System.out.println("time taken is "+ (new Float(System.currentTimeMillis()- time))/1000);
        
        time = System.currentTimeMillis();
        ICAT icatPort = icatService.getICATPort();
        System.out.println("time taken is "+ (new Float(System.currentTimeMillis()- time))/1000);
        
        time = System.currentTimeMillis();
        icatPort = icatService.getICATPort();
        System.out.println("time taken is "+ (new Float(System.currentTimeMillis()- time))/1000);
    }
    
    @Test
    public void timeTest(){
        System.out.println("Singleton test");
        long time = System.currentTimeMillis();
        ICAT port = ICATSingleton.getInstance("https://volga.dl.ac.uk:8181/ICATService/ICAT?wsdl");
        System.out.println("time taken is "+ (new Float(System.currentTimeMillis()- time))/1000);
        System.out.println( ((BindingProvider)port).getRequestContext().get(BindingProvider.ENDPOINT_ADDRESS_PROPERTY));
        
        time = System.currentTimeMillis();
        ICAT port2 = ICATSingleton.getInstance("https://volga.dl.ac.uk:7181/ICATService/ICAT?wsdl");
        System.out.println("time taken is "+ (new Float(System.currentTimeMillis()- time))/1000);
        System.out.println( ((BindingProvider)port2).getRequestContext().get(BindingProvider.ENDPOINT_ADDRESS_PROPERTY));
        
        time = System.currentTimeMillis();
        ICAT port3 = ICATSingleton.getInstance("https://tiber.dl.ac.uk:7181/ICATService/ICAT?wsdl");
        System.out.println("time taken is "+ (new Float(System.currentTimeMillis()- time))/1000);
        System.out.println( ((BindingProvider)port3).getRequestContext().get(BindingProvider.ENDPOINT_ADDRESS_PROPERTY));
        
        time = System.currentTimeMillis();
        port = ICATSingleton.getInstance("https://tiber.dl.ac.uk:7181/ICATService/ICAT?wsdl");
        System.out.println("time taken is "+ (new Float(System.currentTimeMillis()- time))/1000);
        System.out.println( ((BindingProvider)port).getRequestContext().get(BindingProvider.ENDPOINT_ADDRESS_PROPERTY));
        
        port = ICATSingleton.getInstance("https://new.dl.ac.uk:7181/ICATService/ICAT?wsdl");
        
        System.out.println( ((BindingProvider)port).getRequestContext().get(BindingProvider.ENDPOINT_ADDRESS_PROPERTY));
        port = ICATSingleton.getInstance("https://other.dl.ac.uk:7181/ICATService/ICAT?wsdl");
        
        System.out.println( ((BindingProvider)port).getRequestContext().get(BindingProvider.ENDPOINT_ADDRESS_PROPERTY));
        
    }
    
    /**
     * suite method automatically generated by JUnit module
     */
    public static junit.framework.Test suite(){
        return new JUnit4TestAdapter(TestICATSingleton.class);
    }
}
