//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.06.06 at 12:17:03 BST 
//


package edu.sdsc.matrix.srb.parser;


/**
 * Java content class for Container complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="Container">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="containerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currentSize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="maxSize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="replicaNum" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="resourceUsed" type="{http://www.teragrid.org/schemas/datagrid}Resource" minOccurs="0"/>
 *         &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface Container {


    java.lang.String getDataType();

    void setDataType(java.lang.String value);

    java.math.BigInteger getMaxSize();

    void setMaxSize(java.math.BigInteger value);

    int getReplicaNum();

    void setReplicaNum(int value);

    edu.sdsc.matrix.srb.parser.Resource getResourceUsed();

    void setResourceUsed(edu.sdsc.matrix.srb.parser.Resource value);

    java.math.BigInteger getCurrentSize();

    void setCurrentSize(java.math.BigInteger value);

    java.lang.String getContainerName();

    void setContainerName(java.lang.String value);

}
