.\" For ascii version, process this file with
.\" groff -man -Tascii S.1
.\"
.TH S 1 "Jan 2003 " "Storage Resource Broker" "Tape Admin Commands"
.SH NAME
S \- .
.SH SYNOPSIS
.B S
.RB [ \-v ]
.SH DESCRIPTION
.B "S "

.sp

.sp

.PP
.SH "OPTIONS"
.TP 0.5i
.B "\-h "
display command options
.TP 0.5i
.B "\-u "

.TP 0.5i
.B "\-s "

.TP 0.5i
.B "\-V "

.TP 0.5i
.B "\-d "

.SH "SEE ALSO"
.BR S (1),
.BR S (1),
.BR S (1),
.BR S (1),
.BR S (1)