#!/bin/csh -ex
set LIBDIR = ./lib 
set AIDLIBDIR = /usr/local/apps/aid/lib
set GSILIBDIR = /usr/local/apps/gsi/lib
set SSLEAYLIBDIR =  /usr/local/apps/ssleay/lib
cc -c -o sample_main.o sample_main.c
cc -o mysrb2.cgi sample_main.o $LIBDIR/libMySRB.a $LIBDIR/libSrbClient.a -lm -lpthread -L $AIDLIBDIR -laid -L $GSILIBDIR -lglobus_gss_assist -lglobus_gss -lglobus_gaa -L $SSLEAYLIBDIR -lssl -lcrypto -lbsm -lintl -z muldefs -lm
